version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "build phase started"
      - mvn clean package -Pprod -DskipTests
  post_build:
    commands:
      - mv target/*.jar ./good-bank.jar

artifacts:
  files:
    - good-bank.jar
